---
- name: Check if SELinux is installed
  stat:
    path: /usr/sbin/sestatus
  register: selinux_installed
  changed_when: false

- name: Check SELinux status (when installed)
  command: sestatus
  register: selinux_status
  changed_when: false
  ignore_errors: true
  when: selinux_installed.stat.exists

- name: Disable SELinux if enabled and installed
  block:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
      become: true
      register: selinux_disabled

    - name: Reboot if SELinux was disabled
      reboot:
        msg: "Reboot initiated after disabling SELinux"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      become: true
      when: selinux_disabled is changed
  when:
    - selinux_installed.stat.exists
    - "'disabled' not in selinux_status.stdout|default('')"
