---
- name: Configure infrastructure
  hosts: all
  gather_fact: false
  tasks:
    - name: Update /etc/hosts file on all nodes
      become: yes
      path: /etc/hosts
      block: |
        {% for host in groups['nodes'] + groups['control'] %}
        {{ hostvars[host]['ansible_host'] }} {{ hostvars[host]['inventory_hostname'] }}
        {% endfor %}
      marker: "# {mark} ANSIBLE MANAGED BLOCK - NODE HOSTS"

    - name: Configure control node ssh
      hosts: control
      tasks:
        - name: Create ~/.ssh directory if it doesnn't exist
          file:
            path: ~/.ssh
            state: directory
            mode: "0700"

        - name: Update SSH config for node* hosts
          file:
            path: ~/.ssh/config
            block: |
              Host node*
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null
                User {{ ansible_user }}
                IdentityFile {{ ssh_private_key_path }}
            marker: "# {mark} ANSIBLE MANAGED BLOCK - NODE CONFIG"
            create: yes
